### Obtener todos los usuarios
GET http://localhost:5241/usuarios
Accept: application/json

### Obtener un usuario por mail
GET http://localhost:5241/usuarios/ana%40example.com
Accept: application/json

### Obtener un usuario por mail con mail inexistente
GET http://localhost:5241/usuarios/1
Accept: application/json

### Crear un usuario
POST http://localhost:5241/usuarios
Content-Type: application/json

{
  "mail": "carla@example.com",
  "nombre": "Carla",
  "apellido": "López"
}

### Crear un usuario con mail invalido
POST http://localhost:5241/usuarios
Content-Type: application/json

{
  "mail": "carla@examplecom",
  "nombre": "Carla",
  "apellido": "López"
}

### Actualizar un usuario
PUT http://localhost:5241/usuarios/ana%40example.com
Content-Type: application/json

{
  "mail": "ana@example.com",
  "nombre": "Ana",
  "apellido": "Pérez"
}

### Eliminar un usuario
DELETE http://localhost:5241/usuarios/luis%40example.com
