### Get users
GET http://localhost:5241/users?authenticated=true
Accept: application/json

### Get user by id
GET http://localhost:5241/users/1?authenticated=true
Accept: application/json

### Get user by id with non-existent id
GET http://localhost:5241/users/3?authenticated=true
Accept: application/json

### Create user
POST http://localhost:5241/users?authenticated=true
Content-Type: application/json

{
  "mail": "carla@example.com",
  "name": "Carla",
  "lastname": "López",
  "id": 3
}

### Create user with invalid mail
POST http://localhost:5241/users?authenticated=true
Content-Type: application/json

{
  "mail": "carla@examplecom",
  "name": "Carla",
  "lastname": "López",
  "id": 3
}

### Create user with invalid name
POST http://localhost:5241/users?authenticated=true
Content-Type: application/json

{
  "mail": "carla@example.com",
  "name": "Carla1",
  "lastname": "López",
  "id": 3
}

### Update user
PUT http://localhost:5241/users/1?authenticated=true
Content-Type: application/json

{
  "mail": "ana@example.com",
  "name": "Ana",
  "lastname": "Pérez"
}

### Delete user
DELETE http://localhost:5241/users/2?authenticated=true